/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.menu.Menu',
        'Ext.menu.Separator',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Split',
        'Ext.toolbar.Spacer'
    ],

    id: 'viewport',
    itemId: 'viewport',
    margin: '0 0 0 0',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    border: '0 2 0 0',
                    hidden: true,
                    id: 'menuPanel',
                    itemId: 'menuPanel',
                    width: 205,
                    bodyBorder: false,
                    collapseDirection: 'left',
                    collapsible: true,
                    header: false,
                    title: 'Menu',
                    dockedItems: [
                        {
                            xtype: 'menu',
                            dock: 'top',
                            stateful: true,
                            floating: false,
                            itemId: 'sideMenu',
                            frameHeader: false,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    stateful: true,
                                    frame: false,
                                    id: 'myprofile',
                                    itemId: 'myprofile',
                                    href: '#myprofile',
                                    hrefTarget: '_self',
                                    iconCls: 'menu_profile',
                                    text: 'My Profile'
                                },
                                {
                                    xtype: 'menuitem',
                                    stateful: true,
                                    frame: false,
                                    itemId: 'changepassword',
                                    margin: '0 0 0 25',
                                    padding: ' 0 0 0 20',
                                    href: '#changepassword',
                                    hrefTarget: '_self',
                                    iconCls: 'key',
                                    text: 'Change Password'
                                },
                                {
                                    xtype: 'menuseparator'
                                },
                                {
                                    xtype: 'menuitem',
                                    id: 'myplan',
                                    itemId: 'myplan',
                                    href: '#myplan',
                                    hrefTarget: '_self',
                                    iconCls: 'menu_category',
                                    text: 'Manage My Plan'
                                },
                                {
                                    xtype: 'menuitem',
                                    margin: '0 0 0 25',
                                    href: '#txnhistory',
                                    hrefTarget: '_self',
                                    iconCls: 'menu_actor',
                                    text: 'Transaction History'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margins: '',
                    region: 'center',
                    split: true,
                    id: 'contentPanel',
                    itemId: 'contentPanel',
                    margin: '',
                    autoScroll: true,
                    bodyBorder: true,
                    frameHeader: false,
                    header: false,
                    title: 'Content',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 5,
                            right: 5,
                            bottom: 5,
                            left: 5
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    border: false,
                    frame: true,
                    height: 81,
                    id: 'headerPanel',
                    itemId: 'headerPanel',
                    layout: 'anchor',
                    bodyBorder: false,
                    frameHeader: false,
                    header: false,
                    title: 'headerPanel',
                    dockedItems: [
                        {
                            xtype: 'image',
                            dock: 'left',
                            height: 70,
                            margin: '5 5 5 5 ',
                            width: 201,
                            src: 'resources/pixelriver_logo.png'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'right',
                            frame: false,
                            itemId: 'headerToolBar',
                            style: 'background-color:#4c72a4;',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'tbfill',
                                    frame: true
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'login',
                                    href: '#login',
                                    hrefTarget: '_self',
                                    text: 'Login'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'signup',
                                    href: '#signup',
                                    hrefTarget: '_self',
                                    text: 'Sign Up'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 60,
                                    hidden: true,
                                    id: 'profileHeaderImage',
                                    itemId: 'profileHeaderImage',
                                    width: 90,
                                    src: './resources/user-icon.png'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'splitbutton',
                                    hidden: true,
                                    id: 'logoutMenu',
                                    itemId: 'logoutMenu',
                                    href: '',
                                    text: 'Lokesh Deshmukh',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'myprofile',
                                                href: '#myprofile',
                                                hrefTarget: '_self',
                                                iconCls: 'menu_profile',
                                                text: 'My Profile'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'logoutmenuItem',
                                                itemId: 'logoutmenuItem',
                                                href: '',
                                                hrefTarget: '_self',
                                                iconCls: 'key',
                                                text: 'Log out'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'image',
                            height: 55,
                            hidden: true,
                            margin: '10 10 10 10 ',
                            width: 201,
                            src: 'resources/CTA_Header_Cloud_R1.png'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    html: '',
                    margin: '',
                    style: 'border-top: 1px solid #4c72a4',
                    header: false,
                    title: 'footerPanel',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            width: 150,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    href: '#about',
                                    hrefTarget: '_self',
                                    text: 'About'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    href: '#customers',
                                    hrefTarget: '_self',
                                    text: 'Customers'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    href: '#plans',
                                    hrefTarget: '_self',
                                    text: 'Plans'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    href: '#sales',
                                    hrefTarget: '_self',
                                    text: 'Sales'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    href: '#feedbacks',
                                    hrefTarget: '_self',
                                    text: 'Feedbacks'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    href: '#support',
                                    hrefTarget: '_self',
                                    text: 'Support'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 10
                                },
                                {
                                    xtype: 'image',
                                    height: 22,
                                    width: 25,
                                    src: 'resources/facebook.png'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 22,
                                    width: 25,
                                    src: 'resources/twitter.png'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 22,
                                    width: 25,
                                    src: 'resources/blog.png'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 22,
                                    width: 25,
                                    src: 'resources/youtube.png'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 24,
                                    width: 25,
                                    src: 'resources/linkedin.jpg'
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});