/*
 * File: app/view/accountconfirm/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.accountconfirm.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.accountconfirm',

    requires: [
        'Ext.form.field.Display'
    ],

    bodyPadding: 10,
    header: false,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'displayfield',
                    height: 50,
                    itemId: 'accountconfirmMsg',
                    width: 727,
                    value: 'Thanks for registering at Pixel River! We are glad you have chosen to be a part of our community and we hope you enjoy your stay.<br/><br/> All the best, Pixel River Technology <br/><br/> <a href="#login">Click here to login</a> '
                }
            ]
        });

        me.callParent(arguments);
    }

});