/*
 * File: app/view/changepassword/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.changepassword.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.changepassword',

    requires: [
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 250,
    width: 323,
    bodyPadding: 10,
    title: 'Change Password',
    titleAlign: 'center',

    layout: {
        type: 'table',
        columns: 2
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                margin: '20 0 0 25',
                msgTarget: 'under'
            },
            items: [
                {
                    xtype: 'textfield',
                    colspan: 2,
                    itemId: 'oldPassword',
                    width: 250,
                    name: 'oldPassword',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Old Password *'
                },
                {
                    xtype: 'textfield',
                    colspan: 2,
                    itemId: 'password',
                    width: 250,
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'New Password *'
                },
                {
                    xtype: 'textfield',
                    validator: function(value) {
                        var password1 = this.previousSibling('[name=password]');
                        return (value === password1.getValue()) ? true : 'Passwords do not match.';
                    },
                    colspan: 2,
                    itemId: 'confirmPassword',
                    width: 250,
                    name: 'confirmPassword',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Confirm New Password *'
                },
                {
                    xtype: 'button',
                    itemId: 'resetpassword',
                    margin: '20 0 0 115',
                    width: 63,
                    text: 'Reset'
                },
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'submitpassword',
                    width: 66,
                    text: 'Submit'
                }
            ]
        });

        me.callParent(arguments);
    }

});