/*
 * File: app/view/forgotpassword/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.forgotpassword.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.forgotpassword',

    requires: [
        'Ext.form.field.Display',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 280,
    width: 364,
    bodyPadding: 10,
    title: 'Forgot Password',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    itemId: 'forgotpasslabel',
                    value: 'Enter your E-Mail address and we will send you a link to reset your password'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'forgotpassemail',
                    margin: '15 0 0 0 ',
                    width: 430,
                    name: 'forgotpassemail',
                    emptyText: 'Enter your Email Address'
                },
                {
                    xtype: 'button',
                    itemId: 'forgotpasssubmit',
                    margin: '10 0 0 250',
                    width: 90,
                    text: 'Send Link'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    height: 50,
                    itemId: 'forgotpassmsg',
                    margin: '15 0 0 0'
                }
            ]
        });

        me.callParent(arguments);
    }

});