/*
 * File: app/view/passrecovery/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.passrecovery.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.passrecovery',

    requires: [
        'Ext.form.field.Display',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 250,
    width: 331,
    bodyPadding: 10,
    title: 'Reset Password',
    titleAlign: 'center',

    layout: {
        type: 'table',
        columns: 1
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                margin: '5 10 10 20',
                msgTarget: 'under'
            },
            items: [
                {
                    xtype: 'displayfield',
                    itemId: 'resetpassmsg',
                    value: 'Please enter your new password here.'
                },
                {
                    xtype: 'textfield',
                    itemId: 'password',
                    width: 268,
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Password',
                    maxLength: 10,
                    minLength: 6
                },
                {
                    xtype: 'textfield',
                    validator: function(value) {
                        var password1 = this.previousSibling('[name=password]');
                        return (value === password1.getValue()) ? true : 'Passwords do not match.';
                    },
                    itemId: 'confirmPassword',
                    width: 266,
                    name: 'confirmPassword',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Confirm Password'
                },
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'resetpasssubmit',
                    margin: '10 0 0 210',
                    width: 75,
                    text: 'Submit'
                }
            ]
        });

        me.callParent(arguments);
    }

});