/*
 * File: app/store/MyPlan/UnSelected.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyPlan.UnSelected', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.MyPlan.UnSelected',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.MyPlan.UnSelected',
            storeId: 'MyPlan.UnSelected',
            proxy: {
                type: 'ajax',
                url: 'rpcphp/packages/unselected.php',
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'items'
                }
            }
        }, cfg)]);
    }
});