/*
 * File: app/view/myplan/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.myplan.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myplan',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.View'
    ],

    height: 665,
    width: 1148,
    bodyPadding: 10,
    title: 'Manage My Plan',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'panelSelectedPlan',
                    layout: 'fit',
                    collapseFirst: false,
                    collapsible: true,
                    title: 'Selected Plan',
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'gridSelectedPlan',
                            itemId: 'gridSelectedPlan',
                            header: false,
                            title: 'My Grid Panel',
                            store: 'MyPlan.Selected',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 40,
                                    text: 'Sr No.'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_packages',
                                    text: 'id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 210,
                                    dataIndex: 'package_name',
                                    text: 'Package Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 165,
                                    dataIndex: 'activation_dt',
                                    text: 'Activation Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 165,
                                    dataIndex: 'expire_dt',
                                    text: 'Expire Date'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'activation_fee',
                                    text: 'Activation Fee',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'periodical_fee',
                                    text: 'Periodical Fee',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'period',
                                    text: 'Period'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (!value)
                                        {

                                            return '<img src="resources/Subscribed.png"/>';

                                            //  return '<span style="color:green;"><b> Subscribed </b></span>';
                                        }
                                        else
                                        {
                                            return '<img src="resources/UnSubscribed.png"/>';
                                            //  return '<span style="color:red;"><b> Un Subscribed </b></span>';
                                        }
                                    },
                                    align: 'center',
                                    dataIndex: 'IsSubscribed',
                                    text: 'Is Subscribed'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                        if (record.get('IsSubscribed')) {
                                            var linkToPayPal = "php/paypal/payments/CreatePaymentUsingPayPal.php?pkgId=" + record.get('id'),
                                                link = 'Subscribe Now';
                                            return '<a href="' + linkToPayPal + '"><span style="color:green;"><b> <img src="https://www.paypalobjects.com/webstatic/en_US/btn/btn_buynow_pp_142x27.png"/> </b></span></a>';
                                        }
                                        else
                                        return '<span style="color:red;"><b>  </b></span>';

                                    },
                                    width: 170,
                                    align: 'right',
                                    dataIndex: 'IsSubscribed'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'panelUnSelectedPlan',
                    layout: 'fit',
                    collapseFirst: false,
                    collapsible: true,
                    title: 'Un-selected Plan',
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'gridUnSelectedPlan',
                            itemId: 'gridUnSelectedPlan',
                            header: false,
                            title: 'My Grid Panel',
                            store: 'MyPlan.UnSelected',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 43,
                                    text: 'Sr No.'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_packages',
                                    text: 'id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 206,
                                    dataIndex: 'name',
                                    text: 'Package Name'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 116,
                                    dataIndex: 'activation_fee',
                                    text: 'Activation Fee',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 124,
                                    dataIndex: 'periodical_fee',
                                    text: 'Periodical Fee',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        return value;
                                    },
                                    dataIndex: 'period',
                                    text: 'Period'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var linkToPayPal = "php/paypal/payments/CreatePaymentUsingPayPal.php?pkgId=" + record.get('id'),
                                            link = 'Subscribe Now';
                                        return '<a href="' + linkToPayPal + '"><span style="color:green;"><b><img src="https://www.paypalobjects.com/webstatic/en_US/btn/btn_buynow_pp_142x27.png"/>  </b></span></a>';

                                    },
                                    width: 170,
                                    align: 'center',
                                    dataIndex: 'IsSubscribed',
                                    text: ''
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});