/*
 * File: app/view/about/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.about.Index', {
    extend: 'Ext.form.Panel',

    frame: true,
    height: 279,
    html: '<center> <h2>About Pixel River Technology</h2></center>',
    width: 484,
    bodyBorder: true,
    bodyPadding: 10,
    frameHeader: false,
    overlapHeader: false,
    title: 'About us : We have yet to implement this part of the application',
    titleAlign: 'left',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});