/*
 * File: app/controller/accountconfirm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.accountconfirm', {
    extend: 'Ext.app.Controller',

    Index: function() {
        this.getApplication().getController('BaseSession').EnableGuestView();

        //check if link is expired
        var urlHalves = String(document.location).split('?');
         var Halves = urlHalves[1].split('#');

          Ext.Ajax.request({
             url: 'php/accountConfirm.php',
             method: 'GET',
             params:{
                      esource: Halves[0]
                    },
             success: function(conn, response, options, eOpts)
              {
                   var result = MyApp.util.Util.decodeJSON(conn.responseText);

                   if (result.success)
                   {


                   }

              }});

    }

});
