/*
 * File: app/controller/BaseSession.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.BaseSession', {
    extend: 'Ext.app.Controller',

    ValidateSession: function() {
        Ext.Ajax.request({
                        url: 'php/IsSessionAlive.php',
                        method: 'GET',
                        success: function(conn, response, options, eOpts) {

                            var appHeader = Ext.ComponentQuery.query('#headerPanel')[0];

                            var tb = appHeader.down('tbfill');
                            var logout = appHeader.down('#logoutMenu');
                            var profileHeaderImage = appHeader.down('#profileHeaderImage');
                            var loginButton  = appHeader.down('#login');
                            var signupButton =  appHeader.down('#signup');
                            var menuPanel = Ext.ComponentQuery.query('#menuPanel')[0];

                            var result = MyApp.util.Util.decodeJSON(conn.responseText);

                            logout.setText(result.profileEmail);


                            if(result.success)
                            {

                                 profileHeaderImage.setSrc('resources/ProfileImages/'+result.profilePicture);
                                 logout.setVisible(true);
                                 menuPanel.setVisible(true);
                                 profileHeaderImage.setVisible(true);

                                 loginButton.setVisible(false);
                                 signupButton.setVisible(false);

                                if(result.PPStatus === 'PP_SUCCESS')
                                {

                                      Ext.Msg.show({
                                        title:'Transaction was done successfully',
                                        msg: 'Your payment was done successfully. Thanks for your business!',
                                        buttons: Ext.Msg.OK,
                                        icon: Ext.Msg.INFO
                                    });

                                    Ext.Ajax.request({
                                    url: 'php/PPStatusSet.php',
                                    method: 'GET',
                                    success: function(conn, response, options, eOpts) {

                                    }});

                                }



                            }
                            else
                           {
                               profileHeaderImage.setSrc('resources/user-icon.png');
                                 logout.setVisible(false);
                                 menuPanel.setVisible(false);
                                 profileHeaderImage.setVisible(false);

                                 loginButton.setVisible(true);
                                 signupButton.setVisible(true);

                                 Ext.Router.redirect('login');
                           }


                        }});
    },

    EnableGuestView: function() {
        Ext.Ajax.request({
                        url: 'php/IsSessionAlive.php',
                        method: 'GET',
                        success: function(conn, response, options, eOpts) {

                            var appHeader = Ext.ComponentQuery.query('#headerPanel')[0];

                            var tb = appHeader.down('tbfill');
                            var logout = appHeader.down('#logoutMenu');
                            var profileHeaderImage = appHeader.down('#profileHeaderImage');
                            var loginButton  = appHeader.down('#login');
                            var signupButton =  appHeader.down('#signup');
                            var menuPanel = Ext.ComponentQuery.query('#menuPanel')[0];

                            var result = MyApp.util.Util.decodeJSON(conn.responseText);

                            menuPanel.setVisible(false);

                            logout.setText(result.profileEmail);

                            if(result.success)
                            {
                                profileHeaderImage.setSrc('resources/ProfileImages/'+result.profilePicture);
                                 logout.setVisible(true);
                                 profileHeaderImage.setVisible(true);

                                 loginButton.setVisible(false);
                                 signupButton.setVisible(false);
                            }
                            else
                            {
                                profileHeaderImage.setSrc('resources/user-icon.png');
                                 logout.setVisible(false);
                                 profileHeaderImage.setVisible(false);

                                 loginButton.setVisible(true);
                                 signupButton.setVisible(true);
                            }


                        }});
    }

});
