/*
 * File: app/controller/Changepassword.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Changepassword', {
    extend: 'Ext.app.Controller',

    init: function(application) {
          this.control({ "button#submitpassword": { click: this.onButtonClickSubmit } });
                this.control({ "button#resetpassword": { click: this.onButtonClickReset } });
    },

    onButtonClickSubmit: function(button, e, options) {
         var formPanel = button.up('panel'),
                    changePassword = button.up('changepassword');

                var oldPassword = formPanel.down('textfield[name=oldPassword]').getValue();

                var password = formPanel.down('textfield[name=password]').getValue();

                var confirmPassword = formPanel.down('textfield[name=confirmPassword]').getValue();
                //var fomr = formPanel.getForm();
                //alert(fomr);

                 if (formPanel.getForm().isValid()) {
                //  alert('called');
                Ext.get(changePassword.getEl()).mask("Processing your request... Please wait...", 'loading');

                Ext.Ajax.request(
                    {

                        url: 'php/changePass.php',
                        params:
                        {
                            confirmPassword: MyApp.util.MD5.encode(confirmPassword),
                            password: MyApp.util.MD5.encode(password),
                            oldPassword: MyApp.util.MD5.encode(oldPassword)
                        },
                     success: function(conn, response, options, eOpts) {

                                   Ext.get(changePassword.getEl()).unmask();

                                    var result = MyApp.util.Util.decodeJSON(conn.responseText);

                                    if (result.success) {

                                        Ext.get(changePassword.getEl()).unmask();

                                        Ext.Msg.show
                                          ({
                                              title: 'Success..',
                                              msg: 'Your changes updated successfully!',
                                              icon: Ext.Msg.INFORMATION,
                                              buttons: Ext.Msg.OK
                                          });

                                        formPanel.getForm().reset();
                                    }
                                  else
                                  {
                                          Ext.get(changePassword.getEl()).unmask();

                                      Ext.Msg.show
                                ({
                                    title: 'failed..!',
                                    msg: 'Invalid credentials found',
                                    icon: Ext.Msg.ERROR,
                                    buttons: Ext.Msg.OK
                                });

                                    }
                                },
                           failure:function(conn,response,options,eOpts)
                            {
                               Ext.get(changePassword.getEl()).unmask();

                                Ext.Msg.show
                                ({
                                    title: 'Error!',
                                    msg: conn.responseText,
                                    icon: Ext.Msg.ERROR,
                                    buttons: Ext.Msg.OK
                                });



                            }
                        }
                   );
                 }
    },

    onButtonClickReset: function(button, e, options) {
        button.up('form').getForm().reset();
    },

    Index: function() {
        this.getApplication().getController('BaseSession').ValidateSession();
    }

});
