/*
 * File: app/controller/Forgotpassword.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Forgotpassword', {
    extend: 'Ext.app.Controller',

    Index: function() {
        this.getApplication().getController('BaseSession').EnableGuestView();
    },

    init: function(application) {
        this.control(
                    {
                     "forgotpassword button#forgotpasssubmit":
                     {click:this.onButtonClickSubmit}
                    });
    },

    onButtonClickSubmit: function(button, options) {
        var formPanel = button.up('form'),
                     forgotpassword = button.up('forgotpassword'),
                     msgBox =formPanel.down('#forgotpassmsg'),
            forgotpasslabel =formPanel.down('#forgotpasslabel'),
                     email = formPanel.down('textfield[name=forgotpassemail]').getValue();

                if(formPanel.getForm().isValid())
                {
                    Ext.get(forgotpassword.getEl()).mask("Sending Email...", 'loading');
                    Ext.Ajax.request(
                        {
                        url:'php/forgotpass.php',
                        params:
                        {
                            email:email

                        },
                         success: function(conn, response, options, eOpts) {

                                   Ext.get(forgotpassword.getEl()).unmask();

                                    var result = MyApp.util.Util.decodeJSON(conn.responseText);

                                    if (result.success) {

                                        formPanel.down('textfield[name=forgotpassemail]').setVisible(false);
                                        formPanel.down('#forgotpasssubmit').setVisible(false);

                                        forgotpasslabel.setVisible(false);
                                        msgBox.setValue("An e-mail has been sent to the mentioned e-mail address.<br/> The e-mail contains the instructions for resetting your password.<br/> If you don't receive this e-mail, please check your junk mail folder or contact us at TBD@pixelriver.com for further assistance.!", false);
                                        msgBox.show();
                                    }
                                  else {
                                        msgBox.setValue("Incorrect Email Address", false);
                                        msgBox.show();
                                     }
                                },
                           failure:function(conn,response,options,eOpts)
                            {
                               Ext.get(forgotpassword.getEl()).unmask();

                                Ext.Msg.show
                                ({
                                title:'Error!',
                                msg:conn.responseText,
                                icon:Ext.Msg.ERROR,
                                buttons:Ext.Msg.OK
                                });



                            }
                        }
                       );
                }
    }

});
