/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Login', {
    extend: 'Ext.app.Controller',

    requires: [
        'MyApp.util.Util',
        'MyApp.util.SessionMonitor',
        'MyApp.util.MD5'
    ],

    Index: function() {
        this.getApplication().getController('BaseSession').EnableGuestView();

    },

    init: function(application) {

        this.control(
                    {
                     "login button#submit":
                     {click:this.onButtonClickSubmit}
                    });
    },

    onButtonClickSubmit: function(button, e, options) {

        var formPanel = button.up('form'),
                     login = button.up('login'),
                      errorBox =formPanel.down('#loginErrorBox'),
                     user = formPanel.down('textfield[name=user]').getValue(),
                     pass = formPanel.down('textfield[name=password]').getValue();

                //  alert(errorBox);
                if(formPanel.getForm().isValid())
                {
                    Ext.get(login.getEl()).mask("Authenticating...", 'loading');
                    Ext.Ajax.request(
                        {
                        url:'php/checkLogin.php',
                        params:
                        {user:user,
                         password:MyApp.util.MD5.encode(pass)
                        },
                         success: function(conn, response, options, eOpts) {

                                   Ext.get(login.getEl()).unmask();

                                    var result = MyApp.util.Util.decodeJSON(conn.responseText);

                                    if (result.success) {

                                        MyApp.util.SessionMonitor.start();
                                        Ext.state.Manager.set("loggedUserName", user);
                                        Ext.state.Manager.set("IsUserloggedIn", 'YES');
                                        var appHeader = Ext.ComponentQuery.query('#headerPanel')[0];

                                        var tb = appHeader.down('tbfill');
                                        var logout = appHeader.down('#logoutMenu');

                                        var loginButton  = appHeader.down('#login');
                                        var signupButton =  appHeader.down('#signup');
                                        logout.setText(Ext.state.Manager.get("loggedUserName"));
                                        logout.setVisible(true);
                                        loginButton.setVisible(false);
                                        signupButton.setVisible(false);

                                        var menuPanel = Ext.ComponentQuery.query('#menuPanel')[0];

                                        menuPanel.setVisible(true);


                                      //var contentPanel = Ext.ComponentQuery.query('#contentPanel')[0];
                                     //   contentPanel.destroy();

                                      // Ext.create('MyApp.view.contentPanel', {pack:'start'});


                                     // Ext.apply(Ext.ComponentQuery.query('#contentPanel')[0], {pack:'start'});

                                     // appHeader.down('#profileHeaderImage').setSrc('resources/ProfileImages/profile_106.jpg');


                                      Ext.Router.redirect('myprofile');


                                    }
                                  else {
                                        errorBox.setText("Incorrect Email Address or Password", false);
                                        errorBox.show();
                                       /* Ext.Msg.show
                                            ({
                                            title:'Error!',
                                            msg:"Incorrect Email Address or Password",
                                            icon:Ext.Msg.ERROR,
                                            buttons:Ext.Msg.OK
                                            });
                                           */


                                    }
                                },
                           failure:function(conn,response,options,eOpts)
                            {
                               Ext.get(login.getEl()).unmask();

                                Ext.Msg.show
                                ({
                                title:'Error!',
                                msg:conn.responseText,
                                icon:Ext.Msg.ERROR,
                                buttons:Ext.Msg.OK
                                });



                            }
                        }
                       );
                }
    }

});
