/*
 * File: app/controller/Logout.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Logout', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control(
                    {
                     "#logoutmenuItem":
                     {click:this.onButtonClickLogout}
                    });
    },

    onButtonClickLogout: function(button, e, options) {

        Ext.Ajax.request({

                    url:'php/logout.php',

                    success:function(conn,response,options,eOpts)
                    {
                        var result= MyApp.util.Util.decodeJSON(conn.responseText,true);
                        if(!result)
                        {
                            result = {};
                            result.success = false;
                            result.msg = conn.responseText;
                        }

                        if(result.success)
                        {

                            //Clear the cookie
                            Ext.state.Manager.clear("loggedUserName");
                            Ext.state.Manager.clear("IsUserloggedIn");


                            Ext.Router.redirect('login');
                        }
                        else
                        {
                            Ext.Msg.show(
                                {
                                    title:'Error!' ,
                                    msg:result.msg,
                                    icon:Ext.Msg.ERROR,
                                    buttons:Ext.Msg.OK
                                });
                        }
                    },
                    failure:function(conn,response,options,eOpts)
                        {
                         Ext.Msg.show(
                                {
                                    title:'Error!' ,
                                    msg:conn.responseText,
                                    icon:Ext.Msg.ERROR,
                                    buttons:Ext.Msg.OK
                                });
                        }
                });
    }

});
