/*
 * File: app/controller/passrecovery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.passrecovery', {
    extend: 'Ext.app.Controller',

    Index: function() {
        this.getApplication().getController('BaseSession').EnableGuestView();

        //check if link is expired
        var urlHalves = String(document.location).split('?');
         var Halves = urlHalves[1].split('#');

          Ext.Ajax.request({
             url: 'php/IsPassRecoveryExp.php',
             method: 'GET',
             params:{
                      esource: Halves[0]
                    },
             success: function(conn, response, options, eOpts)
              {

                   var result = MyApp.util.Util.decodeJSON(conn.responseText);

                   if (result.success)
                   {

                       Ext.Router.redirect('login');

                   }

              }});

    },

    init: function(application) {
        this.control(
                    {
                     "passrecovery button#resetpasssubmit":
                     {click:this.onButtonClickSubmit}
                    });
    },

    onButtonClickSubmit: function(button, options) {
         var formPanel = button.up('panel'),
             passrecovery = button.up('passrecovery'),
             msgBox =formPanel.down('#resetpassmsg');

         var password = formPanel.down('textfield[name=password]').getValue();
         var confirmPassword = formPanel.down('textfield[name=confirmPassword]').getValue();

         var urlHalves = String(document.location).split('?');
         var Halves = urlHalves[1].split('#');

         if (formPanel.getForm().isValid()) {

                Ext.get(passrecovery.getEl()).mask("Processing your request... Please wait...", 'loading');

                Ext.Ajax.request(
                    {

                        url: 'php/passRecovery.php',
                        params:
                        {
                            password: MyApp.util.MD5.encode(password),
                            esource: Halves[0]
                        },
                     success: function(conn, response, options, eOpts) {

                                   Ext.get(passrecovery.getEl()).unmask();

                                    var result = MyApp.util.Util.decodeJSON(conn.responseText);

                                    if (result.success) {

                                        formPanel.down('textfield[name=confirmPassword]').setVisible(false);
                                        formPanel.down('textfield[name=password]').setVisible(false);
                                        formPanel.down('#resetpasssubmit').setVisible(false);

                                        //forgotpasslabel.setVisible(false);
                                        msgBox.setValue("You have reset your password successfully.", false);
                                        msgBox.show();
                                    }
                                  else
                                  {
                                          Ext.get(passrecovery.getEl()).unmask();

                                      Ext.Msg.show
                                ({
                                    title: 'failed..!',
                                    msg: 'Sorry, we cannot process your request at this moment. Please try later..',
                                    icon: Ext.Msg.ERROR,
                                    buttons: Ext.Msg.OK
                                });

                                    }
                                },
                           failure:function(conn,response,options,eOpts)
                            {
                               Ext.get(passrecovery.getEl()).unmask();

                                Ext.Msg.show
                                ({
                                    title: 'Error!',
                                    msg: conn.responseText,
                                    icon: Ext.Msg.ERROR,
                                    buttons: Ext.Msg.OK
                                });



                            }
                        }
                   );
                 }
    }

});
