/*
 * File: app/controller/Session.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Session', {
    extend: 'Ext.Base',

    validateSession: function() {
        alert('Base called');
        Ext.Ajax.request({
                        url: 'php/IsSessionAlive.php',
                        method: 'GET',
                        success: function(conn, response, options, eOpts) {

                             var appHeader = Ext.ComponentQuery.query('#headerPanel')[0];

                                        var tb = appHeader.down('tbfill');
                                        var logout = appHeader.down('#logoutMenu');
                                        var loginButton  = appHeader.down('#login');
                                        var signupButton =  appHeader.down('#signup');

                            var result = MyApp.util.Util.decodeJSON(conn.responseText);
                            if(result.success)
                            {

                                        logout.setVisible(true);
                                        loginButton.setVisible(false);
                                        signupButton.setVisible(false);

                                        var menuPanel = Ext.ComponentQuery.query('#menuPanel')[0];

                                        menuPanel.setVisible(true);
                            }
                            else
                            {

                                        logout.setVisible(false);
                                        loginButton.setVisible(true);
                                        signupButton.setVisible(true);

                                        var menuPanel = Ext.ComponentQuery.query('#menuPanel')[0];

                                        menuPanel.setVisible(false);

                            }


                        }});
    }

});