/*
 * File: app/view/txnhistory/Index.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.txnhistory.Index', {
    extend: 'Ext.form.Panel',
    alias: 'widget.txnhistory',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.View'
    ],

    height: 576,
    width: 889,
    layout: 'fit',
    bodyPadding: 10,
    title: 'My Transaction History',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'gridPanelTxnHistory',
                    itemId: 'gridPanelTxnHistory',
                    header: false,
                    title: 'My Grid Panel',
                    emptyText: 'Sr No.',
                    store: 'TraxnHistory',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 47,
                            text: 'Sr No.'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 183,
                            dataIndex: 'transaction_refrence_no',
                            text: 'Transaction Refrence No'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'price',
                            text: 'Amount',
                            format: '0.00'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 148,
                            dataIndex: 'updated_datetime',
                            text: 'Updated Date Time'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 129,
                            dataIndex: 'transaction_state',
                            text: 'Transaction State'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});